[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "merge_dna"
version="0.0.1"
description = "mergeDNA reimplementation"
dependencies = [
    "torch",
    "matplotlib",
    "numpy"
]